export const siteConfig = {
  name: "D'RENTALS | Professional Cinema Equipment by Penmen Studios",
  description:
    "Rent professional cinema cameras, lenses, and accessories for your production from Penmen Studios in Hyderabad, India.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://rentals.penmenstudios.com",
  ogImage: "https://rentals.penmenstudios.com/og-image.jpg",
  links: {
    twitter: "https://twitter.com/penmenstudios",
    instagram: "https://instagram.com/penmenstudios",
  },
  keywords: [
    "camera rental",
    "camera rentals in hyderabad",
    "4k camera for rent in hyderabad",
    "5d camera rent in hyderabad",
    "camera equipment rental in hyderabad",
    "camera lens for rent in hyderabad",
    "camera rent in kukatpally",
    "camera rental in dilsukhnagar",
    "camera rental kukatpally",
    "camera rentals in hyderabad dslr cameras for rent",
    "camera rentals in hyderabad near me",
    "canon 5d mark iv rent in hyderabad",
    "cinema camera rentals in hyderabad",
    "dslr camera for rent hyderabad",
    "dslr camera on rent hyderabad",
    "dslr camera rentals in hyderabad",
    "dslr on rent in hyderabad camera rentals",
    "dslr on rent in hyderabad",
    "dslr rent in hyderabad",
    "gimbal for rent in hyderabad",
    "gimbal rent in hyderabad",
    "gimbal rental hyderabad",
    "gopro camera for rent in hyderabad",
    "gopro for rent hyderabad",
    "gopro for rent in hyderabad",
    "gopro rent hyderabad",
    "gopro rent in hyderabad",
    "gopro rental in hyderabad",
    "hyd camera rentals",
    "hyderabad camera rental",
    "hyderabad rental camera",
    "lens for rent in hyderabad",
    "lens rental in hyderabad",
    "nikon lens for rent in hyderabad",
    "red camera rent in hyderabad",
    "red camera rental hyderabad",
    "red epic camera rental in hyderabad",
    "rent dslr camera in hyderabad",
    "video camera for rent in hyderabad",
    "cinema equipment",
    "film equipment",
    "camera gear",
    "professional cameras",
    "cinema lenses",
    "lighting equipment",
    "audio equipment",
    "film production",
    "video production",
    "camera accessories",
    "Hyderabad",
    "India",
    "Penmen Studios",
    "RED camera rental",
    "ARRI camera rental",
    "Sony camera rental",
    "Canon camera rental",
    "Blackmagic camera rental",
    "cinema camera rental near me",
    "RED Komodo rental Hyderabad low price",
    "mirrorless camera rental in Hyderabad",
    "DSLR on rent for travel Hyderabad",
    "camera rental for one day Hyderabad",
    "BMPCC 6K Pro body only rental",
    "video camera rental service Hyderabad",
    "pocket cinema camera rental Hyderabad",
    "best place to rent camera for shoot",
    "hire camera for music video Hyderabad",
    "low cost camera rental Hyderabad",
    "short film camera gear Hyderabad",
    "student short film equipment on rent",
    "camera and gimbal combo for rent",
    "rent gear for short film shoot in Hyderabad",
    "shooting equipment for short film Hyderabad",
    "filmmaking kit rental Hyderabad",
    "low budget filmmaking kit Hyderabad",
    "DOP equipment rental Hyderabad",
    "pre production camera rental",
    "cinematography kit for hire Hyderabad",
    "studio light rental Hyderabad",
    "film lighting kit for rent",
    "LED panel lights on rent Hyderabad",
    "RGB film lights rental Hyderabad",
    "Godox continuous light rental",
    "photography lighting rental Hyderabad",
    "shoot light rental with stand Hyderabad",
    "softbox light rental Hyderabad",
    "cob light rental Hyderabad",
    "digitek 60w light on rent",
    "camera gimbal on rent Hyderabad",
    "rent DJI RS 3 Pro gimbal Hyderabad",
    "slider for cinematic shots Hyderabad",
    "tripod rental Hyderabad",
    "fluid head tripod on rent",
    "shoulder rig rental Hyderabad",
    "stabilizer for short film shoot Hyderabad",
    "fog machine rental Hyderabad",
    "dry ice effect machine rental",
    "smoke machine hire Hyderabad",
    "film sound accessories rental",
    "mic and boom pole rental Hyderabad",
    "audio recorder rental for shoots",
    "drone for video shoot rental Hyderabad",
    "DJI Air 2S rental Hyderabad",
    "drone on rent for wedding shoot",
    "aerial shots drone hire Hyderabad",
    "rent drone with pilot Hyderabad",
    "camera rentals for film students Hyderabad",
    "budget camera rental for college project",
    "DSLR on rent for student filmmaking",
    "affordable camera gear for beginners",
    "student discount on rentals Hyderabad",
    "low budget filmmaking kit Hyderabad",
    "DSLR rental in Mehdipatnam",
    "camera on rent in Ameerpet",
    "video gear rental in Tarnaka",
    "gimbal for rent in Uppal",
    "camera rental shop Manikonda",
    "Kondapur video equipment rentals",
    "Madhapur camera rental service",
    "pre wedding shoot equipment Hitech City",
    "Jubilee Hills lens and gimbal rentals",
    "best camera rental service in Hyderabad",
    "where to rent camera and lights for short film",
    "film equipment near me for rent",
    "shoot-ready gear rental in Hyderabad",
    "RED Komodo rental with lens",
    "hire BMPCC camera and gimbal",
    "which place gives DSLR on rent in Hyderabad",
    "complete short film package rental",
    "weekend camera rental deals Hyderabad",
    "lights and fog machine combo rental",
  ],
  location: {
    address: "Rajeev nagar, yousufguda, hyderabad, 500045",
    region: "Telangana",
    country: "India",
    phone: "+91 7794872701",
    email: "rentals@penmenstudios.com",
  },
  business: {
    name: "D'RENTALS by Penmen Studios",
    type: "CameraStore",
    openingHours: "Mo-Su 00:00-23:59", // Updated to 24/7
    priceRange: "₹₹₹",
    areas: ["Hyderabad", "Kukatpally", "Dilsukhnagar", "Telangana"],
  },
}
